server:
  port: 12354
redis:
  host: ${REDIS.HOST}
spring:
  profiles:
    active: jdbc
  datasource:
#    url: jdbc:postgresql://${POSTGRES.HOST}:${POSTGRES.PORT:5432}/${POSTGRES.SCHEMA}
#    username: user
#    password: password
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  flyway:
    locations:
      - classpath:sql
    sqlMigrationPrefix: v
  h2:
    console.enabled: true
